spring:
  application:
    name: jpa-study

  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: user
    password:

  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console # 접속 주소: http:/localhost:9095/h2-console

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    # 콘솔에 SQL 로그 출력 설정
    properties:
      hibernate:
        format_sql: true    # SQL을 정렬해서 보여줌
        show_sql: true      # 실행되는 SQL을 콘솔에 출력
        highlight_sql: true # SQL 키워드에 색상 입히기

server:
  port: 9095