spring:
  application:
    name: jpa-study

  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console # 접속 주소: http:/localhost:9095/h2-console

  jpa:
    # 실행 시점에 테이블을 어떻게 할 것인가? (create: 매번 새로 생성, update: 변경분만 반영)
    hibernate:
      ddl-auto: update
    # 콘솔에 SQL 로그 출력 설정
    properties:
      hibernate:
        format_sql: true    # SQL을 예쁘게 정렬해서 보여줌
        show_sql: true      # 실행되는 SQL을 콘솔에 출력
        highlight_sql: true # SQL 키워드에 색상 입히기 (Spring Boot 2.x 후반~3.x 지원)

        # (선택) 파라미터 바인딩 값(?)을 보고 싶다면 추가 설정이 필요하지만,
        # 기본 JPA 설정으로는 '?'로만 나옵니다. (P6Spy 라이브러리 추천)

server:
  port: 9095